### ISSUE TITLE
Add new user and change password methods

### ISSUE THREAD

**Issue by sam-travise** [zeldan/spring-boot-oauth2-jwt#2]
This is a very great project. Can you add or point to how to create new user and the change password methods?
Thanks

**Comment by zeldan** [comment]
Hi, 
I updated the readme, add FAQ into the end of the note. If you have any question, feel free to ask.

**Comment by sam-travise** [comment]
Yes, I meant it will be great to have a web service to create new user and password, change password, and refresh token. 
Thank you
